project:
  type: website

website:
  title: "ibe-dashboard"
  favicon: images/ibe.png
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: dashboard.qmd
        text: Dashboard
      - href: IBE_Dashboard_MH.qmd
        text: Apresentação (MH)
format:
  html:
    theme: [sandstone, custom.scss]
    toc: true



